import React from 'react';

export const warehouseRoutes = [
  {
    path: '/warehouse',
    name: 'home',
    title: 'Warehouse home',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../pages/Home')),
    isLayout: false,
    isGuarded: false,
  },
  {
    path: '/warehouse/new-request-goods-note',
    name: 'home',
    title: 'New Request',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../../../modules/warehouse/pages/CreateRequestGoodsNote')),
    isLayout: false,
    isGuarded: false,
  },
  {
    path: '/warehouse/request-goods-note-cart/manage',
    name: 'home',
    title: 'Manage Request',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../../../modules/warehouse/pages/Manage')),
    isLayout: false,
    isGuarded: false,
  },
  {
    path: '/warehouse/new-request-goods-note-cart',
    name: 'home',
    title: 'Warehouse home',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../../../modules/warehouse/pages/CreateRequestGoodsCartPage')),
    isLayout: false,
    isGuarded: false,
  },
  {
    path: '/warehouse/request-goods-note/edit/:orderID',
    name: 'home',
    title: 'Edit Request',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../../../modules/warehouse/pages/Edit')),
    isLayout: false,
    isGuarded: false,
  },
  {
    path: '/warehouse/manage',
    name: 'home',
    title: 'New Request',
    exact: true,
    permission: '',
    component: React.lazy(() => import('../../../modules/admin-warehouse/pages/Manage')),
    isLayout: false,
    isGuarded: false,
  },
];
